name: Docker Build and Push

on:
  push:
    branches:
      - main
      - cian

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: docker:latest

    steps:
    - name: Install Docker CLI
      run: |
        apk add --no-cache docker-cli

    # 2. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 3. Docker 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    # 4. Docker 이미지 빌드 및 푸시
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.IMAGENAME }}:latest
